### ISSUE TITLE
Doc available?

### ISSUE THREAD

**Issue by jch02140** [julian-linux/material-ui-react-hook-form-builder#1]
Hi,

Just wondering if there is a API doc available with the list of supported form fields and the properties?

**Comment by julian-linux** [comment]
every prop in material-ui inputs

**Comment by jch02140** [comment]
Thank you for the reply. 

I tried to use the `variant='outlined'` prop for the text input field but the label seems to offset from the original position.


You can see an example here:
https://codesandbox.io/s/interesting-thompson-eho44?file=/src/config.js

**Comment by julian-linux** [comment]
i just updated a new version fixing that and updated some documentation.
Hope it help you.

**Comment by jch02140** [comment]
Thanks will re-check again
